# Generated by Django 2.2 on 2019-06-11 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_auto_20190611_1433'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.Building')),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.Building'),
        ),
    ]
