# Generated by Django 2.2 on 2019-06-11 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_auto_20190611_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='item.Building'),
        ),
    ]
