# Generated by Django 2.2 on 2019-06-06 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_auto_20190606_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/'),
        ),
    ]
