# Generated by Django 2.2 on 2019-06-06 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_auto_20190606_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='building',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
