# Generated by Django 2.2 on 2019-06-08 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0007_auto_20190606_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='time',
        ),
        migrations.AddField(
            model_name='item',
            name='retrieved_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
