# Generated by Django 2.2 on 2019-06-09 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0011_auto_20190608_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='building',
            field=models.CharField(default='unknown', max_length=20),
        ),
    ]
