# Generated by Django 2.2 on 2019-06-09 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0013_auto_20190609_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='building',
            field=models.IntegerField(default=0),
        ),
    ]
